config/routes.rb
Rails.application.routes.draw do
  resources :event_sign_ins
  root 'home#index'
  
  resources :users do
  	member do
  		post :toggle_admin
  		post :toggle_dues
  		#get 'toggle_admin', to: 'users#toggle_admin', as: 'toggle_admin'
  	end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_sign_in.rb
class EventSignIn < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/event_sign_ins_controller.rb
class EventSignInsController < ApplicationController
  before_action :set_event_sign_in, only: [:show, :edit, :update, :destroy]

  # GET /event_sign_ins
  # GET /event_sign_ins.json
  def index
    @event_sign_ins = EventSignIn.all
  end

  # GET /event_sign_ins/1
  # GET /event_sign_ins/1.json
  def show
  end

  # GET /event_sign_ins/new
  def new
    @event_sign_in = EventSignIn.new
  end

  # GET /event_sign_ins/1/edit
  def edit
  end

  # POST /event_sign_ins
  # POST /event_sign_ins.json
  def create
    @event_sign_in = EventSignIn.new(event_sign_in_params)
    @event_sign_in.event_date = Time.now

    respond_to do |format|
      if @event_sign_in.save
        format.html { redirect_to @event_sign_in, notice: 'Event sign in was successfully created.' }
        format.json { render :show, status: :created, location: @event_sign_in }
      else
        format.html { render :new }
        format.json { render json: @event_sign_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_sign_ins/1
  # PATCH/PUT /event_sign_ins/1.json
  def update
    respond_to do |format|
      if @event_sign_in.update(event_sign_in_params)
        format.html { redirect_to @event_sign_in, notice: 'Event sign in was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_sign_in }
      else
        format.html { render :edit }
        format.json { render json: @event_sign_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_sign_ins/1
  # DELETE /event_sign_ins/1.json
  def destroy
    @event_sign_in.destroy
    respond_to do |format|
      format.html { redirect_to event_sign_ins_url, notice: 'Event sign in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_sign_in
      @event_sign_in = EventSignIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_sign_in_params
      params.require(:event_sign_in).permit(:event_email, :event_password, :event_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged in!"
  	else
  		flash.now[:alert] = "Email or password is invalid"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_admin
      @user = User.find_by_id(params[:id])
      @user.update_attribute :admin, true
      redirect_to users_url, notice: 'User is now an admin.'
  end
  
  def toggle_dues
      @user = User.find_by_id(params[:id])
      @user.update_attribute :dues, true
      redirect_to users_url, notice: 'User dues have been marked as paid.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_sign_ins_helper.rb
module EventSignInsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_sign_ins/_form.html.erb
<%= form_with(model: event_sign_in, local: true) do |form| %>
  <% if event_sign_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_sign_in.errors.count, "error") %> prohibited this event_sign_in from being saved:</h2>

      <ul>
      <% event_sign_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_email %>
    <%= form.text_field :event_email, id: :event_sign_in_event_email %>
  </div>

  <div class="field">
    <%= form.label :event_password %>
    <%= form.text_field :event_password, id: :event_sign_in_event_password %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/event_sign_ins/edit.html.erb
<h1>Editing Event Sign In</h1>

<%= render 'form', event_sign_in: @event_sign_in %>

<%= link_to 'Show', @event_sign_in %> |
<%= link_to 'Back', event_sign_ins_path %>

app/views/event_sign_ins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Sign Ins</h1>

<% if current_user.try(:admin?) %>

  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Password</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @event_sign_ins.each do |event_sign_in| %>
        <tr>
          <td><%= event_sign_in.event_email %></td>
          <td><%= event_sign_in.event_password %></td>
          <td><%= event_sign_in.event_date %></td>
          <td><%= link_to 'Destroy', event_sign_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Event Sign In', new_event_sign_in_path %>
<% else %>
  <p>You do not have permission to access this page </p>
<% end %>
<br> 
<%= link_to 'Back to home page', root_path %>

app/views/event_sign_ins/new.html.erb
<h1>New Event Sign In</h1>

<%= render 'form', event_sign_in: @event_sign_in %>

<%= link_to 'Back', event_sign_ins_path %>

app/views/event_sign_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event email:</strong>
  <%= @event_sign_in.event_email %>
</p>

<p>
  <strong>Event password:</strong>
  <%= @event_sign_in.event_password %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event_sign_in.event_date %>
</p>

<%= link_to 'Edit', edit_event_sign_in_path(@event_sign_in) %> |
<%= link_to 'Back', event_sign_ins_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>
<h1>TACS Events</h1>
<p>Welcome to TACS</p>

<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
  
  <% if current_user.try(:admin?) %>
  	<p>
  	Admin privileges
  	<br>
  	<%= link_to 'Edit Users', users_path %>
  	<br>
  	<%= link_to 'View Event Attendance', event_sign_ins_path %>
  </p>
  <% end %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>
<br>
<br>
<%= link_to 'Event Sign In', new_event_sign_in_path %>
<p>
<iFrame src="https://calendar.google.com/calendar/b/3/embed?height=526&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=tamu.edu_ad54lcc88gu8lclb6t8h61dr40%40group.calendar.google.com&amp;color=%23875509&amp;ctz=America%2FChicago" style="border-width:0" width="600" height="526" frameborder="0" scrolling="no"></iframe>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TACS event registration</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<% if current_user.try(:admin?) %>
    <%= button_to 'Make User An Officer', toggle_admin_user_path(@user), data: { confirm: 'Are you sure?' }%>
    <br>
    <%= button_to 'Mark Dues as Paid', toggle_dues_user_path(@user) %>
<%end%>
<br/>



<br>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<% if current_user.try(:admin?) %>
  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Dues</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.dues %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  
  <%= link_to 'New User', new_user_path %>
<% else %>
  <p>You do not have permission to access this page </p>
<% end %>
<br> 
<%= link_to 'Back to home page', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
  <br>
  <strong>Dues paid? </strong>
  <% if @user.dues %>
    Dues are paid!
  <%else%>
    Dues are not paid.
  <%end%>
  <br>
  <strong>Admin?</strong>
  <%if @user.admin %>
    User is admin!
  <%else%>
    Not an admin!
  <%end%>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>